# First, add the API
apiVersion: apps/v1
# This will be the deployment setup
kind: Deployment
metadata:
  # Name your Deployment here
  name: blazor-app-kube
  labels:
    # label your deployment
    app: blazor-app-kube-test
spec:
  # The number of pods/replicas to run
  replicas: 1
  selector:
    matchLabels:
    # selector to match the pod
      app: blazor-app-kube-test
  template:
    metadata:
      labels:
      # label your pod
        app: blazor-app-kube-test
    spec:
      containers:
      # Add the container name for Kubernetes
      - name: blazor-super-app
      # Add the local image name
        image: blazorappdocker
        # never pull the image policy
        imagePullPolicy: Never
        ports:
        # port for running the container, le port sur lequel l'application du conteneur roule
        - containerPort: 80
---
# First, add the Service API
apiVersion: v1
# This will be the Service setup
kind: Service
metadata:
  # Your service name
  name: blazor-app-src
spec:
  selector:
    # selector that matches the pod
    app: blazor-app-kube-test
  # type of service
  type: LoadBalancer
  ports:
  - protocol: TCP
    # port for exposing the service
    port: 5000
    # portfor exposing the pod
    targetPort: 80
    # port for exposing the node
    nodePort: 31110